
FROM ubuntu
LABEL maintainer="youta1119 <dev.youta1119@gmail.com>"
LABEL version="1.0"
LABEL description="i386-elf toolchain"
RUN mkdir /root/work
WORKDIR /root/work
RUN apt-get -y update && apt-get -y install curl make gcc

#install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
ENV PATH $PATH:/root/.cargo/bin
RUN cargo install xargo
RUN rustup component add rust-src

#make binutils
ARG BINUTILS_VERSION="2.21.1"
RUN curl -SL https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.bz2 | tar xj -C ./
RUN cd ./binutils-${BINUTILS_VERSION} && \
    ./configure --prefix=/usr/local --target=i386-jos-elf --disable-werror  && \
    make -s -j8 && \
    make install && \ 
    rm -rf ../binutils-${BINUTILS_VERSION}


